# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sunLight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

post_install do |installer|
    # 需要指定编译版本的第三方的名称
    myTargets = ['ObjectMapper', 'SnapKit']
    
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end

  use_frameworks!

# 约束框架
pod 'SnapKit', '~> 3.0'
# 网络框架
pod 'AFNetworking'
# 加载指示器
pod 'SVProgressHUD'
# 网络图片加载
pod 'SDWebImage’

# Pods for sunLight

end
